function initializeDAQparam

%create structure to hold parameters
DAQparam = struct('waveName','wave1',...
    'scanLength',Inf,...
    'interval',1,...
    'dwellTime',0.02,...
    'pointNumber',1,...
    'photonCounter',0,...
    'recordA',0,...
    'recordB',0,...
    'pHmeter',0,...
    'pH',0,...
    'cond',0,...
    'measurePower',0,...
    'NIDAQ',0,...
    'EPM',0,...
    'autoPause',0,...
    'flowcontrol',0,...
    'pump',0);

%store it in root under DAQparam
setappdata(0,'DAQparam',DAQparam)
display('DAQparam inititalized.')

%get address of DAQ
%DAQ = daq.getDevices;
%setappdata(0,'DAQ',DAQ)

%set up NI daq session
daqSess = daq.createSession('ni');
%add reading analog voltage from channel 1 (differential?)
addAnalogInputChannel(daqSess,'Dev1',0,'Voltage');
daqSess.Rate = 2000; % 2000 readings a second
daqSess.DurationInSeconds = 0.1; % for 0.1 seconds

setappdata(0,'DAQsession',daqSess);




end