function initializeDAQparam

%create structure to hold parameters
DAQparam = struct('waveName','wave1',...
    'scanLength',Inf,...
    'photonCounter',0,...
    'recordA',0,...
    'recordB',0,...
    'pHmeter',0,...
    'pH',0,...
    'cond',0,...
    'measurePower',0,...
    'NIDAQ',0,...
    'EPM',0,...
    'autoPause',0,...
    'flowcontrol',0,...
    'pump',0);

%store it in root under DAQparam
setappdata(0,'DAQparam',DAQparam)
display('DAQparam inititalized.')


end